### ISSUE TITLE
Translate the text in the README.md

### ISSUE THREAD

**Issue by AndrewDya** [test-form/sem3-git#1]
Translate the text in the README.md file into English. And add that the remaining tasks have been completed

**Comment by Andrewdyac** [comment]
ok, sure. 10 min

**Comment by Andrewdyac** [comment]
https://github.com/test-form/sem3-git/pull/2 task complete in 10 min

**Comment by AndrewDya** [comment]
Changes have been made, branch deleted. Thank you for your work.
